# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 149cc2ed921ce4f4bb1632fee25cdfda0c5eeca57f2df59288243b384dd4054cd69af19714c08fd7b5ca836ff780c885467f9f5ce3547ff7a08617e673f4aa47

test:
  secret_key_base: 3845f2fb84a460eae8f557ca7e297cc06fa20d412fcb4227deef205571ea00e3f48c53f9b72ca2f0710b04fdd252ef52108f6d848b38572bd9e9b9a59bf195b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
