# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cf01706cfbf7d294543277e09df7675946372eefdc877011321436026a7548613f371867c0032b0bfe8c67796f9375f38e6528f8a93070616447d7c79fa1248

test:
  secret_key_base: 60947238e0fd2000d2bc1e0af65ae9b48b56ea6e84a0b2c84de22658d52f0d0f0897a9f20a138bc3496f7eaee7858bf94658b2b717344b8018e4c77f7cae0147

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
